### PR TITLE
Refactor using a base widget class

### PR DESCRIPTION
**Pull request by caguero**
~~For now, it's working for the rotational and dial gauges. `Dial` needs a bit more work.~~

All gauges should be functional.

### CODE REVIEW

**Comment by ahcorde** [comment]
@caguero is this ready for review?

**Comment by caguero** [comment]
> @caguero is this ready for review?

Not yet.

**Comment by caguero** [comment]
> > @caguero is this ready for review?
> 
> Not yet.

Good to go!

**Review by ahcorde — CHANGES_REQUESTED** [review]
- In the dial the units are not working
 - the minimum value in the rotational widge should be -45 and not 0

**Comment by caguero** [comment]
> * In the dial the units are not working
> * the minimum value in the rotational widge should be -45 and not 0

It should be fixed in [d5ebb40](https://github.com/ToyotaResearchInstitute/gauges2/pull/35/commits/d5ebb40e851c5f8097792de82483b2d09adfe918)

**Comment by ahcorde** [comment]
gauges_not_wroking

- min value in rotational is not working
- min and max values not working on bar gauges

**Review by ahcorde — CHANGES_REQUESTED** [review]
see comment

**Comment by caguero** [comment]
> fcd44f5

I tweaked the limits in some widgets. Could you check now?

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
